CONTIKI_PROJECT = external_sensors
all: $(CONTIKI_PROJECT)
CONTIKI_TARGET_SOURCEFILES += adc-sensors.c weather-meter.c grove-gyro.c
#UIP_CONF_IPV6=1


CONTIKI = $(HOME)/contiki
CONTIKI_WITH_RIME = 1
include $(CONTIKI)/Makefile.include
