CONTIKI_PROJECT = external_sensors
all: $(CONTIKI_PROJECT)

#UIP_CONF_IPV6=1


CONTIKI = $(HOME)/contiki
CONTIKI_WITH_RIME = 1

CFLAGS += -DPROJECT_CONF_H=\"project-conf.h\"

include $(CONTIKI)/Makefile.include
